### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by tupperward** [thunderysteak/EveryHourBot#2]
I'd like to run this from a container so I can slap it in my k3s cluster and go "check out all these pictures minor league baseball team alternative team logos".

I'm more than happy to do the work for this.

**Comment by thunderysteak** [comment]
Bot can now be containerized with merged PR https://github.com/thunderysteak/EveryHourBot/pull/3

Will look into setting up Github Actions for CI/CD Dockerhub publishing when I have free time

**Comment by thunderysteak** [comment]
CI action to publish to docker hub now live
https://hub.docker.com/r/thunderysteak/everyhourbot
