### ISSUE TITLE
Documentation doesnt cover setting up an application on mastodon like it does with twitter api

### ISSUE THREAD

**Issue by greenisacolour** [thunderysteak/EveryHourBot#5]
I'm having an issue with setting up bot, it outputs: "Error creating Toot: TypeError [ERR_INVALID_URL]: Invalid URL" which is caused by a invalid redirect URL on the mastodon application but ive never handled oauth 2.0 before so im not entirely sure what URL i should be using

edit: it turns out i was completely wrong and i just put the URL in the .env file incorrectly (no https:// ), it would still be nice to have instructions in the readme.md for mastodon though

**Comment by thunderysteak** [comment]
Updated readme file to mention the URL formatting needed for the mastodon server variable formatting in https://github.com/thunderysteak/EveryHourBot/commit/f3e25ce244c5cf8ff7bc8fcf0f9b8277fa9d60db
