### ISSUE TITLE
Error creating tweet: [object Object] in log, no tweet sent

### ISSUE THREAD

**Issue by greenisacolour** [thunderysteak/EveryHourBot#6]
For context I run "FerretPerHour" on twitter, it was running on Twitters V1 api but got suspended from the that api and I was forced to migrate to the V2 free api. Which was pretty painless and worked out of the box besides some log issues, but recently the bot stopped posting and started logging "Error creating tweet: [object Object]" multiple times over in the logs

`/home/green/.pm2/logs/FerretEveryHour-error.log last 15 lines:`
`0|FerretEv | Error creating tweet: [object Object]`
`0|FerretEv | Error creating tweet: [object Object]`
`0|FerretEv | Error creating tweet: [object Object]`
`0|FerretEv | Error creating tweet: [object Object]`

I've tried this on two machines and same result. it might be twitter changing something on their end regarding the V2 api, ive seen your posts on masto/twitter about how stressful the whole V2 situation is. so dont worry about fixing this issue immediately since its working flawlessly on mastodon 👍

**Comment by thunderysteak** [comment]
This is unfortunately an issue caused by the upstream npm module having broken v2 support and no longer being maintained. 

A refactor is in works to use a different module

**Comment by thunderysteak** [comment]
Twitter banned bots using the v1 and v2 api on large scale today, unfortunately because of this, Twitter support is now deprecated

**Comment by thunderysteak** [comment]
@greenisacolour bot refactor is now live, please use the new v2.0.0 with API V2 support

**Comment by greenisacolour** [comment]
awesome thank you sm!!
